### PR TITLE
docs(samples): Convert tightly coupled local variable involved options inside of method into method arguments

### LINKED ISSUE #394: docs(samples): Convert tightly coupled local variable involved options inside of method into method arguments
**Is your feature request related to a problem? Please describe.**
As of the current version we can see that more options related to argument
are written inside of the test instead of included as arguments

**Describe the solution you'd like**
As this is tightly coupled with argument, it will be better to pass it as well.

**Describe alternatives you've considered**
N/A

**Additional context**
Any other context or screenshots about the feature request.

### PR DESCRIPTION
**Pull request by irvifa**
As of the current version we can see that more options related to argument
are written inside of the test instead of included as arguments, so I think
as this is tightly coupled with argument, it will be better to pass it as well.

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-bigquery/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #394 ☕️

### CODE REVIEW

**Comment by irvifa** [comment]
@stephaniewang526 is this okay? I saw error on https://source.cloud.google.com/results/invocations/e7ac9071-fdc8-490a-b6cd-015c38028e55/targets;collapsed=/cloud-devrel%2Fclient-libraries%2Fjava%2Fjava-bigquery%2Fpresubmit%2Fjava11-samples/log for only java 11

**Comment by stephaniewang526** [comment]
> @stephaniewang526 is this okay? I saw error on https://source.cloud.google.com/results/invocations/e7ac9071-fdc8-490a-b6cd-015c38028e55/targets;collapsed=/cloud-devrel%2Fclient-libraries%2Fjava%2Fjava-bigquery%2Fpresubmit%2Fjava11-samples/log for only java 11

Thanks -- looks like it was a flaky test. We should probs fix that too.

**Comment by irvifa** [comment]
@stephaniewang526 is it specifically only for that test? Because I can see that the BQ table can’t be found when the test was run.

**Comment by stephaniewang526** [comment]
Yes it's specific to the test -- maybe we need to add UUID to tablename. Sometimes we run tests concurrently and it can cause issues. The same test did not fail in Java 8.

**Pull request merged**
