### PR TITLE
fix: properly handle external table schema on table update

### LINKED ISSUE #2235: BigQuery Updating External table schema with connectionId set throws exception
#### Environment details

1. Specify the API at the beginning of the title. For example, "BigQuery: ...").
   General, Core, and Other are also allowed as types
2. OS type and version: 
3. Java version: 8
4.  version(s): 2.13.8

#### Steps to reproduce

  1. Run BigQuery::update with an external table definition with a schema and connectionId specified
  

#### Code example

```java
bigQuery.update(TableInfo.of(tableId, externalTableDefinition.build()));
```

#### Stack trace
```
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
POST https://www.googleapis.com/bigquery/v2/projects/testing-acme/datasets/staging_env_test_2/tables/device_dataset?prettyPrint=false
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Schema can be specified only on the Table.Schema field for external tables with an associated connection_id but schema was provided on Table.Externaldataconfig.Schema.",
    "reason" : "invalid"
  } ],
  "message" : "Schema can be specified only on the Table.Schema field for external tables with an associated connection_id but schema was provided on Table.Externaldataconfig.Schema.",
  "status" : "INVALID_ARGUMENT"
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:118)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:37)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:439)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1111)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:525)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:466)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:576)
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.patch(HttpBigQueryRpc.java:282)
	... 17 more
```

#### External references such as API reference guides

The issue is that there is different logic when creating vs updating a table:
https://github.com/googleapis/java-bigquery/blob/main/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java#L292-L295
This snippet needs to be added to the update logic. I have validated this with my own testing.

#### Any additional information below

Following these steps guarantees the quickest resolution possible.

Thanks!

### PR DESCRIPTION
**Pull request by the-other-tim-brown**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-bigquery/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #2235 ☕️

If you write sample code, please follow the [samples format](
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md).

### CODE REVIEW

**Comment by Neenu1995** [comment]
Hi @the-other-tim-brown ,
Thanks for opening the PR. Would you mind adding some tests to validate the change?

**Comment by the-other-tim-brown** [comment]
> Hi @the-other-tim-brown , Thanks for opening the PR. Would you mind adding some tests to validate the change?

@Neenu1995 I added some tests, let me know if you want me to add more.

**Comment by the-other-tim-brown** [comment]
@Neenu1995 Can you let me know what else is required for this? You cannot use BigLake and update a schema for an external table without these changes.

**Comment by Neenu1995** [comment]
This looks good to me. I will merge it in time for next release after October 3.
What is BigLake though?

**Comment by the-other-tim-brown** [comment]
> This looks good to me. I will merge it in time for next release after October 3. What is BigLake though?

Big Lake is a new GCP product https://cloud.google.com/biglake - it provides some more features on top of externally backed tables

**Comment by Neenu1995** [comment]
Gotcha. TIL :)
Thanks for opening this PR @the-other-tim-brown. Expect the feature in the October first week release.

**Comment by the-other-tim-brown** [comment]
Thanks @Neenu1995!

**Review by Neenu1995 — APPROVED** [review]

**Pull request merged**
