### PR TITLE
ci: unmanaged dependency check

### PR DESCRIPTION
**Pull request by suztomo**
Cont of https://github.com/googleapis/java-bigquery/pull/3108. Now we have the BOM.

b/320677879

### CODE REVIEW

**Comment by suztomo** [comment]
```
Running Unmanaged Dependency Check against /home/runner/work/java-bigquery/java-bigquery/google-cloud-bigquery-bom/pom.xml
This pull request seems to add new third-party dependency, [org.apache.arrow:arrow-memory-core, org.threeten:threeten-extra, org.apache.arrow:arrow-memory-netty, org.apache.arrow:arrow-vector, org.apache.arrow:arrow-format, com.google.flatbuffers:flatbuffers-java], among the artifacts listed in ./google-cloud-bigquery-bom/pom.xml.
```

**Comment by suztomo** [comment]
Now the shared dependencies BOM has the third-party dependencies (https://github.com/googleapis/java-bigquery/pull/3176, merged). The check should succeed.

**Comment by suztomo** [comment]
"Unmanaged dependency check / unmanaged_dependency_check (pull_request) Successful"

**Review by PhongChuong — APPROVED** [review]

**Comment by suztomo** [comment]
Did I forget to merge this?

**Comment by JoeWang1127** [comment]
> Did I forget to merge this?

I think so.

**Pull request merged**
