### PR TITLE
feat: Allow passing autodetect_schema on table update

### PR DESCRIPTION
**Pull request by emkornfield**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
-  Didn't open an issue because this seems trivial, happy to adapt if necessary.
- [x ] Ensure the tests and linter pass (mvn test verify
- [x ] Code coverage does not decrease (if any source code was changed)
- [x ] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by emkornfield** [comment]
@alvarowolfx seems like you might be a suggested reviewer here?

**Comment by emkornfield** [comment]
@shollyman could you take a look in place of Neenu?  This change is to help a customer resolve an issue they are seeing.

**Review by shollyman — APPROVED** [review]

**Comment by Neenu1995** [comment]
Please also add IT tests to verify the functionality.

**Comment by emkornfield** [comment]
> Please also add IT tests to verify the functionality.

@Neenu1995 I don't appear to have access to the test buckets to verify a unit test.  I can push what I think it likely a working unit test but would likely need your help to verify.  Is there some other way I can formulate a unit test without access to the buckets?

**Comment by Neenu1995** [comment]
Hi @emkornfield,

Feel free to add the tests to the PR. We can help with the verification.

**Comment by emkornfield** [comment]
@Neenu1995 added a first stab at an integration test.

**Comment by Neenu1995** [comment]
```
com.google.cloud.bigquery.BigQueryException: An internal error occurred and the request could not be completed. This is usually caused by a transient issue. Retrying the job with back-off as described in the BigQuery SLA should solve the problem: https://cloud.google.com/bigquery/sla. If the error continues to occur please contact support at https://cloud.google.com/support. Error: 8965006
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:115)
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.patch(HttpBigQueryRpc.java:285)
	at com.google.cloud.bigquery.BigQueryImpl$15.call(BigQueryImpl.java:696)
	at com.google.cloud.bigquery.BigQueryImpl$15.call(BigQueryImpl.java:693)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
	at com.google.cloud.bigquery.BigQueryImpl.update(BigQueryImpl.java:692)
	at com.google.cloud.bigquery.it.ITBigQueryTest.testUpdatePermExternableTableWithAutodetectSchemaUpdatesSchema(ITBigQueryTest.java:1593)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	```

**Comment by Neenu1995** [comment]
Two test failing : 

- testUpdatePermExternableTableWithAutodetectSchemaUpdatesSchema - `java.lang.AssertionError`

- testListTablesWithPartitioning - `java.lang.ClassCastException: com.google.cloud.bigquery.AutoValue_ExternalTableDefinition cannot be cast to com.google.cloud.bigquery.StandardTableDefinition`

**Comment by emkornfield** [comment]
@Neenu1995 got integration test work (at least kokoro seems happy).

**Review by Neenu1995 — APPROVED** [review]

**Comment by Neenu1995** [comment]
Thanks @emkornfield. LGTM.

**Pull request merged**
