### PR TITLE
feat: Add preserveAsciiControlCharacters to CsvOptions

### PR DESCRIPTION
**Pull request by takayahilton**
https://groups.google.com/g/google-cloud-sdk-announce/c/Wf6jcd-_Mm8

### CODE REVIEW

**Comment by takayahilton** [comment]
https://github.com/googleapis/java-bigquery/issues/2142

**Comment by Neenu1995** [comment]
Hi @takayahilton,
Could you please add an integration test?

**Comment by takayahilton** [comment]
@Neenu1995 
Added IT.   Could you check this change?

**Comment by Neenu1995** [comment]
Thanks @takayahilton. LGTM.

**Review by Neenu1995 — APPROVED** [review]

**Pull request merged**
