### PR TITLE
fix: Fixing NPE bug by adding to if clause

### PR DESCRIPTION
**Pull request by nick-redfearn**
Bug fix for NPE

NPE is...
```
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
```

From my stacktrace...
```
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1808)
	at java.base/java.util.regex.Matcher.reset(Matcher.java:461)
	at java.base/java.util.regex.Matcher.(Matcher.java:256)
	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1180)
	at com.google.cloud.bigquery.BigQueryImpl.create(BigQueryImpl.java:436)
	at com.google.cloud.bigquery.BigQueryImpl.create(BigQueryImpl.java:363)
```

Looks like a bad null check to me

### CODE REVIEW

**Review by PhongChuong — APPROVED** [review]

**Comment by PhongChuong** [comment]
Thanks for contributing.
Can you run:
`mvn com.coveo:fmt-maven-plugin:format`
to fix the lint error (line too long).
Otherwise, approved. Just need to run few integration tests prior to merging.

**Review by agrawal-siddharth — APPROVED** [review]

**Review by PhongChuong — APPROVED** [review]

**Comment by PhongChuong** [comment]
@nick-redfearn , this PR is merged. It will be included in the next release. Thank you for your contribution.

**Pull request merged**
